### ISSUE TITLE
frame.zig encode() @memcpy() destination length not (explicitly) defined. (zig 0.12-dev)

### ISSUE THREAD

**Issue by ghost** [ianic/websocket.zig#4]
Using Zig 0.12.0-dev.1879+e19219fa0 I get a run-time error:

zig build
zig-out/bin/wss
thread 74640 panic: @memcpy arguments have non-equal lengths

/websocket.zig/src/frame.zig:190:36: 0x34f87c in encode (wss)
        @memcpy(buf[offset..], self.payload);
 
I'm new to the code but as far as I can see the copy is correct, so I just added the destination length:
frame.zig:190:
@memcpy(buf[offset..payload_end], self.payload);

Running zig-out/bin/wss then returns "hello world"

**Comment by ianic** [comment]
Thanks @jwstolk!
